server:
  port: 8092
  servlet:
    context-path: /api

spring:
  application:
    name: zurich-spring-poc
  datasource:
    url: jdbc:h2:mem:claimdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console



policy-service:
  url: http://localhost:8091/poc
  username: user
  password: password

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.zurich.poc: DEBUG
    org.hibernate: WARN
